Remove duplicate file entry in book/src/SUMMARY.md
pipeline is failing with the following error:
```[cargo-make] INFO - Execute Command: "mdbook" "build" "-d" "../public" "book"
2025-04-30 23:30:55 [ERROR] (mdbook::utils): Error: Summary parsing failed for file="/builds/nvmetal/carbide/book/src/SUMMARY.md"
2025-04-30 23:30:55 [ERROR] (mdbook::utils): 	Caused By: Duplicate file in SUMMARY.md: "playbooks/carbide_web_oauth2.md"
Error while executing command, exit code: 101

Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1```

I found that a recent mdbook update has started enforcing this.
https://github.com/rust-lang/mdBook/pull/2613

See merge request nvmetal/carbide!4007