chore: Use a seperate output directory for debug and release protobuf reflection data
This is another attempt at solving the CI failures for protobuf compilation:
```
error: failed to run custom build command for `rpc v0.0.1 (/workspaces/carbide/rpc)`

Caused by:
  process didn't exit successfully: `/workspaces/carbide/target/release/build/rpc-a8a8125d984cdae4/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=proto/forge.proto
  cargo:rerun-if-changed=proto/machine_discovery.proto
  cargo:rerun-if-changed=proto/security_group.proto
  cargo:rerun-if-changed=proto

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "invalid FileDescriptorSet: failed to decode Protobuf message: FileDescriptorSet.file: buffer underflow" }', rpc/build.rs:125:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

If these failures occur because different builds write the same file,
we can solve it by producing different output files per build.
A benefit of this should be that less rebuilds of the `rpc` crate would
be necessary when switching from debug to release builds, since the
`forge.bin` file wouldn't change.