fix(admin-cli): used typed MacAddress in the CLI
This updates the use of a `String` for a MAC address to being an actual `mac_address::MacAddress`. Now when you try to input a MAC address, if it's bad, you'll get an error:

```
❯ forgecli dev4 expected-machine add --bmc-mac-address lolzzz
error: invalid value 'lolzzz' for '--bmc-mac-address <BMC_MAC_ADDRESS>': invalid length

For more information, try '--help'.
```

Similarly works for `show` and `delete` (where `show` is still optional), and will list all otherwise. What's nice is this ALSO takes care of lowercase vs. uppercase issues on the CLI side, since enforcement of a `MacAddress.to_string()` will always give you uppercase.

```
❯ forgecli dev4 expected-machine show B0:7B:25:D6:5A:7C
ExpectedMachine {
    bmc_mac_address: "B0:7B:25:D6:5A:7C",
    bmc_username: "root",
    bmc_password: "M/uz{HKh@fz6S-%8",
    chassis_serial_number: "F55P1G3",
    fallback_dpu_serial_numbers: [],
}

❯ forgecli dev4 expected-machine show b0:7b:25:d6:5a:7c
ExpectedMachine {
    bmc_mac_address: "B0:7B:25:D6:5A:7C",
    bmc_username: "root",
    bmc_password: "M/uz{HKh@fz6S-%8",
    chassis_serial_number: "F55P1G3",
    fallback_dpu_serial_numbers: [],
}

❯ forgecli dev4 expected-machine show boop
error: invalid value 'boop' for '[BMC_MAC_ADDRESS]': invalid length

For more information, try '--help'.

❯ forgecli dev4 expected-machine show
ExpectedMachineList {
    expected_machines: [
        ExpectedMachine {
            bmc_mac_address: "B0:7B:25:D6:5A:7C",
            bmc_username: "root",
            bmc_password: "M/uz{HKh@fz6S-%8",
            chassis_serial_number: "F55P1G3",
            fallback_dpu_serial_numbers: [],
        },
        ExpectedMachine {
            bmc_mac_address: "38:68:DD:66:4D:69",
            bmc_username: "USERID",
            bmc_password: "PAWW0RD",
            chassis_serial_number: "J101ZR8T",
            fallback_dpu_serial_numbers: [],
        },
    ],
}
```

See merge request nvmetal/carbide!2919