Add Uuid::Error to CarbideError for catching failed uuid conversions
  * Converting from Rust UUID to Protobuf UUID can fail.  Without
  capturing that in CarbideError we get the error

error[E0277]: `?` couldn't convert the error to `CarbideError`
   --> api/src/db/network_segment.rs:113:54
    |
113 |               Some(v) => Some(uuid::Uuid::try_from(v)?),
    |                                                      ^ the trait `From<uuid::Error>` is not implemented for `CarbideError`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
...

  * Don't unwrap the value for subdomain_id when marhsalling data
    protobuf