chore: for your consideration.. make mh show --all an implicit mh show
I type `mh show --all` a lot, and was thinking it might be nice to just
make it so `mh show` works.

By setting `--all` such that it `conflicts_with = "machine"` and setting
a `default_value("")` on `machine`, it seems to give us what we want, in
that you can't do `mh show <machine-id> --all`, and that everything else
still works as intended.

Example case of working with `domain`:
```
chet@groundhog:carbide $ forgecli dev3 domain show d822944a-2fdb-407e-8ad4-78d962255cf2 --all
error: the argument '[DOMAIN]' cannot be used with '--all'

Usage: forge-admin-cli domain show <DOMAIN>

For more information, try '--help'.

chet@groundhog:carbide $ forgecli dev3 domain show
+--------------------------------------+---------------------+-----------------------------+
| Id                                   | Name                | Created                     |
+======================================+=====================+=============================+
| d822944a-2fdb-407e-8ad4-78d962255cf2 | dev3.frg.nvidia.com | 2023-07-24T18:04:49.982631Z |
+--------------------------------------+---------------------+-----------------------------+

chet@groundhog:carbide $ forgecli dev3 domain show d822944a-2fdb-407e-8ad4-78d962255cf2
ID        : d822944a-2fdb-407e-8ad4-78d962255cf2
NAME      : dev3.frg.nvidia.com
CREATED   : 2023-07-24T18:04:49.982631Z
UPDATED   : 2023-07-24T18:04:49.982631Z
DELETED   : 1970-01-01T00:00:00Z

chet@groundhog:carbide $ forgecli dev3 domain show --all
+--------------------------------------+---------------------+-----------------------------+
| Id                                   | Name                | Created                     |
+======================================+=====================+=============================+
| d822944a-2fdb-407e-8ad4-78d962255cf2 | dev3.frg.nvidia.com | 2023-07-24T18:04:49.982631Z |
+--------------------------------------+---------------------+-----------------------------+
2024-02-14T19:49:32.503281Z  WARN forge_admin_cli::domain: redundant `--all` with basic `show` is deprecated, to be removed in a future build.
```

There might be a fancier way to pull this off in *clap* (I was messing
around with `default_value_if` to try to keep the `ArgGroup` in tact (with
the idea I could set a default value on `machine` and allow the requirements
as set by the `ArgGroup` to be met), but it wasn't working.

That brings me to this:
- *If you don't like this idea:* I'm happy to close this MR.
- *If you DO like this idea:* I can do a follow up MR to apply this behavior to
other instances of `--all`.