fix admin-cli machine show empty MachineId bug
## Description
In !4555, I changed the type for the machine_id parameter to `Option<MachineId>`, but left `default_value` at `""`, when it should be `None`, resulting in an error when you type `forge-admin-cli mh show`:

```
error: invalid value '' for '[MACHINE]': The Machine ID has an invalid length of 0
```

Fix by setting default_value to None.

## Type of Change
<!-- Check one that best describes this MR -->
- [ ] **Add** - New feature or capability
- [ ] **Change** - Changes in existing functionality  
- [X] **Fix** - Bug fixes
- [ ] **Remove** - Removed features or deprecated functionality
- [ ] **Internal** - Internal changes (refactoring, tests, docs, etc.)

## Breaking Changes
- [ ] This MR contains breaking changes

## Testing
<!-- How was this tested? Check all that apply -->
- [ ] Unit tests added/updated
- [ ] Integration tests added/updated  
- [x] Manual testing performed
- [ ] No testing required (docs, internal refactor, etc.)

## Additional Notes
Fixes regression introduced in !4555

See merge request nvmetal/carbide!4560