feat: adding a firmware management library for supernics
This introduces an `mlxconfig-firmware` crate alongside all of the other `mlxconfig-` crates that have been slowly accumulating, to which I'm actually planning on folding together into a single crate soon-ish. The primary goal of this is to manage firmware on SuperNICs installed on Carbide hosts, whether they be used for E/W or N/S traffic. Obviously right now we only use SuperNICs for E/W and not N/S, but if we ever "supported" hosts that used a SuperNIC for N/S, we could use this to manage firmware on them.

Includes:
- A nice AI-generated `README.md`!
- Integration with the `mlxconfig-embedded` CLI playground. Not a production tool; merely as a working example of how to interact with the various libraries.

The general overview is as follows:

- **Flash**:
  - We can `flash` a firmware binary from a `file://`, `https://`, or `ssh://` source.
  - We support optional `Credentials` for HTTPS and SSH `FirmwareSource` types.
  - We support optional debug `device_conf` files (for debug firmware) to apply via the `mlxconfig` CLI.
  - The debug "device conf" files also support various `FirmwareSource` and `Credentials`.

- **Verify**:
  - We can `verify-image` to verify the flashed firmware binary on the card matches the input binary file (via `flint`).
  - We can `verify-version` to verify the version we expected to be flashed is the running version (via `mlxfwmanager`).

- **Reset**:
  - We can `reset` the device to load the flashed firmware onto running memory (via `mlxfwreset`).
  - We can `reset-config` of the `mlxconfig` parameters when needing to go back to a default state (via `mlxconfig`).

All configuration can be expressed as `TOML`, which is how we will integrate it into `carbide-api`; I'll be adding that to the config struct in a subseqent PR (see **Out of scope** below).

**Out of scope of this PR:**
- How/where to serve up firmware binaries. The library has support for multiple source types, so however users want to allow `scout` to access the file (local, HTTPS, or SSH) will be a subsequent discussion. This may or may not include if users want to support flashing unreleased debug firmware that cannot [yet] be made public, and how to accommodate that.
- How Carbide will allow users to control config per device SKU. Basic `TOML` support is provided to feed to the library for flashing, but a subsequent PR will deal with how we will enforce mapping specific device firmware to specific SKUs and PSIDs (e.g. PN `900-9D3D4-00EN-HA0` w/ PSID `MT_0000001069` gets a specific BlueField3IB).
- How Carbide will manage orchestrating firmware updates. Obviously this will happen when a host OS is in the `scout` image, where presumably we'll see differing firmware version is expected within the state machine and process accordingly, but again, out of the scope.

TLDR is that this provides the library to enable these things, but integration will be separate.

All functions tested against a `Nvidia BlueField-3 B3140H E-series HHHL SuperNIC`, P/N `900-9D3D4-00EN-HA`, PSID `MT_0000001069`, using public firmware downloaded directly from [NVIDIA Networking Firmware Downloads](https://network.nvidia.com/support/firmware/bluefield3/), made for this specific device.

Here's an example of the library in action using the `mlxconfig-embedded` reference CLI. Note that firmware flashing takes roughly 7 minutes for this device:

```
chet@honeybadger carbide-core on  mlx_firmware_mgmt [!?] via 🦀 v1.90.0
❯ sudo mlxconfig-embedded firmware verify-version 01:00.0 32.43.1014
2026-02-12T23:31:29.010197Z  INFO mlxconfig_embedded::cmd::cmds: Verifying firmware version device=01:00.0 expected=32.43.1014
2026-02-12T23:31:29.504663Z  INFO mlxconfig_embedded::cmd::cmds: Firmware version verified version=32.43.1014

chet@honeybadger carbide-core on  mlx_firmware_mgmt [!?] via 🦀 v1.90.0
❯ sudo mlxconfig-embedded firmware verify-image 01:00.0 fw-BlueField-3-rel-32_43_1014-900-9D3D4-00EN-HA0_Ax-NVME-20.4.1-UEFI-21.4.13-UEFI-22.4.14-UEFI-14.36.16-FlexBoot-3.7.500.signed.bin
2026-02-12T23:31:50.664256Z  INFO mlxconfig_embedded::cmd::cmds: Verifying firmware image device=01:00.0 image=fw-BlueField-3-rel-32_43_1014-900-9D3D4-00EN-HA0_Ax-NVME-20.4.1-UEFI-21.4.13-UEFI-22.4.14-UEFI-14.36.16-FlexBoot-3.7.500.signed.bin
Binary comparison success.

chet@honeybadger carbide-core on  mlx_firmware_mgmt [!?] via 🦀 v1.90.0
❯ sudo mlxconfig-embedded firmware verify-image 01:00.0 fw-BlueField-3-rel-32_42_1000-900-9D3D4-00EN-HA0_Ax-NVME-20.4.1-UEFI-21.4.13-UEFI-22.4.13-UEFI-14.35.15-FlexBoot-3.7.500.signed.bin
2026-02-12T23:32:06.792581Z  INFO mlxconfig_embedded::cmd::cmds: Verifying firmware image device=01:00.0 image=fw-BlueField-3-rel-32_42_1000-900-9D3D4-00EN-HA0_Ax-NVME-20.4.1-UEFI-21.4.13-UEFI-22.4.13-UEFI-14.35.15-FlexBoot-3.7.500.signed.bin
-E- Binary comparison failed - versions mismatch.

chet@honeybadger carbide-core on  mlx_firmware_mgmt [!?] via 🦀 v1.90.0
❯ sudo mlxconfig-embedded firmware verify-version 01:00.0 32.42.1000
2026-02-12T23:32:22.330946Z  INFO mlxconfig_embedded::cmd::cmds: Verifying firmware version device=01:00.0 expected=32.42.1000
Error: Firmware verification failed: Firmware version mismatch on '01:00.0': expected '32.42.1000', found '32.43.1014'

chet@honeybadger carbide-core on  mlx_firmware_mgmt [!?] via 🦀 v1.90.0
❯ sudo mlxconfig-embedded firmware flash 01:00.0 fw-BlueField-3-rel-32_42_1000-900-9D3D4-00EN-HA0_Ax-NVME-20.4.1-UEFI-21.4.13-UEFI-22.4.13-UEFI-14.35.15-FlexBoot-3.7.500.signed.bin
2026-02-12T23:32:32.111463Z  INFO mlxconfig_embedded::cmd::cmds: Flashing firmware device=01:00.0
2026-02-12T23:39:38.994036Z  INFO mlxconfig_embedded::cmd::cmds: Flash complete device=01:00.0 source=local:fw-BlueField-3-rel-32_42_1000-900-9D3D4-00EN-HA0_Ax-NVME-20.4.1-UEFI-21.4.13-UEFI-22.4.13-UEFI-14.35.15-FlexBoot-3.7.500.signed.bin device_conf="none" timestamp=2026-02-12T23:39:38.993968692+00:00

chet@honeybadger carbide-core on  mlx_firmware_mgmt [!?] via 🦀 v1.90.0
❯ sudo mlxconfig-embedded firmware verify-image 01:00.0 fw-BlueField-3-rel-32_42_1000-900-9D3D4-00EN-HA0_Ax-NVME-20.4.1-UEFI-21.4.13-UEFI-22.4.13-UEFI-14.35.15-FlexBoot-3.7.500.signed.bin
2026-02-12T23:39:57.947298Z  INFO mlxconfig_embedded::cmd::cmds: Verifying firmware image device=01:00.0 image=fw-BlueField-3-rel-32_42_1000-900-9D3D4-00EN-HA0_Ax-NVME-20.4.1-UEFI-21.4.13-UEFI-22.4.13-UEFI-14.35.15-FlexBoot-3.7.500.signed.bin
Error: Firmware verification failed: Command execution failed: stdout: -E- Failed to read HW pointers from flash-E- FW image verification failed. AN HCA DEVICE CAN NOT BOOT FROM THIS IMAGE.

chet@honeybadger carbide-core on  mlx_firmware_mgmt [!?] via 🦀 v1.90.0
❯ sudo mlxconfig-embedded firmware reset 01:00.0
2026-02-12T23:40:04.607417Z  INFO mlxconfig_embedded::cmd::cmds: Resetting device device=01:00.0 level=3
2026-02-12T23:40:14.497957Z  INFO mlxconfig_embedded::cmd::cmds: Reset complete

chet@honeybadger carbide-core on  mlx_firmware_mgmt [!?] via 🦀 v1.90.0 took 9s
❯ sudo mlxconfig-embedded firmware verify-image 01:00.0 fw-BlueField-3-rel-32_42_1000-900-9D3D4-00EN-HA0_Ax-NVME-20.4.1-UEFI-21.4.13-UEFI-22.4.13-UEFI-14.35.15-FlexBoot-3.7.500.signed.bin
2026-02-12T23:40:54.257906Z  INFO mlxconfig_embedded::cmd::cmds: Verifying firmware image device=01:00.0 image=fw-BlueField-3-rel-32_42_1000-900-9D3D4-00EN-HA0_Ax-NVME-20.4.1-UEFI-21.4.13-UEFI-22.4.13-UEFI-14.35.15-FlexBoot-3.7.500.signed.bin
Binary comparison success.

chet@honeybadger carbide-core on  mlx_firmware_mgmt [!?] via 🦀 v1.90.0
❯ sudo mlxconfig-embedded firmware verify-version 01:00.0 32.42.1000
2026-02-12T23:41:01.420318Z  INFO mlxconfig_embedded::cmd::cmds: Verifying firmware version device=01:00.0 expected=32.42.1000
2026-02-12T23:41:01.941983Z  INFO mlxconfig_embedded::cmd::cmds: Firmware version verified version=32.42.1000
```

Signed-off-by: Chet Nichols III <chetn@nvidia.com>