Drop unused dependency in carbide-ssh which is causing build failures
## Description
The openssl dependency is causing a build failure building the aws-lc-sys crate:

```
2025-10-28T13:16:42.288837Z 01O   --- stderr
2025-10-28T13:16:42.288837Z 01O   Missing dependency: cmake
2025-10-28T13:16:42.288838Z 01O 
2025-10-28T13:16:42.288838Z 01O   thread 'main' panicked at /opt/rust/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.27.1/builder/main.rs:382:40:
2025-10-28T13:16:42.288839Z 01O   called `Result::unwrap()` on an `Err` value: "Required build dependency is missing. Halting build."
```

I dunno if our build runners used to have cmake and no longer do, but it turns out we don't need this dependency anyway, so drop it.

## Type of Change
- [ ] **Add** - New feature or capability
- [ ] **Change** - Changes in existing functionality  
- [X] **Fix** - Bug fixes
- [ ] **Remove** - Removed features or deprecated functionality
- [ ] **Internal** - Internal changes (refactoring, tests, docs, etc.)

## Breaking Changes
- [ ] This MR contains breaking changes

## Testing
- [ ] Unit tests added/updated
- [ ] Integration tests added/updated  
- [X] Manual testing performed
- [ ] No testing required (docs, internal refactor, etc.)

## Additional Notes

See merge request nvmetal/carbide!4779