add `mlx-device` subcommand to scout for local interaction
## Description

_The primary driver for this is for the DPA integration work,
which is why it's going into `scout`, but I actually intend
for similar features to be integrated into `forge-dpu-agent`
as well, since this also applies to DPUs._

This pulls in the `mlxconfig-device` subcommand (the same one
used by the `mlxconfig-embedded` reference CLI) to provide
local commands for querying Mellanox device information, allowing
us to "see" what Carbide is going to see when `MlxDeviceReport`
updates are set, to verify `DeviceFilter` filtering options, and
just for general visibility (including troubleshooting).

Since this is the first case where `--machine-interface-id`
is **NOT** needed, I made an adjustment to making it such that
`machine_interface_id` is no longer `require(true)`, and instead
will attempt to load it during `initial_setup` (and yell if not),
which allows me to get around it being required (and still make
it required for all other commands that need it).

Tested locally by building `scout` and making sure it reports
back as expected (including `--help` and all of the subcommands)
```
❯ sudo target/debug/forge-scout --mode standalone discovery
level=INFO msg="Running as Standalone...false" location="scout/src/main.rs:81"
Error: --machine-interface-id=<uuid> is required for this subcommand.

Location:
    scout/src/main.rs:94:20
```

```
❯ sudo target/debug/forge-scout --machine-interface-id=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa --mode standalone discovery
level=INFO msg="Running as Standalone...false" location="scout/src/main.rs:81"
level=INFO msg="Trying to register the machine" location="scout/src/main.rs:107"
```

```
❯ sudo target/debug/forge-scout --help
Usage: forge-scout [OPTIONS] [COMMAND]

Commands:
  auto-detect         Fetch command from Forge API server
  deprovision         Run deprovision
  logerror            Send error report to Carbide API
  discovery           Run Discovery
  reset               Run reset
  machine-validation  Machine Validation
  mlx-device          Query local Mellanox device information.
                      This is really only useful when --mode standalone.
                      Also, --machine-interface-id is 'required' due to global
                      args, so pass something, but we ignore it.
  help                Print this message or the help of the given subcommand(s)

Options:
      --version
          Print version number and exit
      --mode <MODE>
          [default: service] [possible values: service, standalone]
  -m, --machine-interface-id <MACHINE_INTERFACE_ID>
          The machine interface ID to send to carbide-api. Most commands need this.
```

```
chet@groundhog carbide on  mlx_device_subcmd_scout [!] via 🦀 v1.88.0
❯ sudo target/debug/forge-scout --mode standalone mlx-device describe 01:00.0
level=INFO msg="Running as Standalone...false" location="scout/src/main.rs:81"
+---------------------------------+-------------------------------------------------------------+
| Field                           | Value                                                       |
+---------------------------------+-------------------------------------------------------------+
| pci_name                        | 01:00.0                                                     |
+---------------------------------+-------------------------------------------------------------+
| base_mac                        | C4:70:BD:A4:EF:EE                                           |
+---------------------------------+-------------------------------------------------------------+
| psid                            | MT_0000001069                                               |
+---------------------------------+-------------------------------------------------------------+
| device_type                     | BlueField3                                                  |
+---------------------------------+-------------------------------------------------------------+
| part_number                     | 900-9D3D4-00EN-HA0_Ax                                       |
+---------------------------------+-------------------------------------------------------------+
| device_description              | Nvidia BlueField-3 B3140H E-series HHHL SuperNIC; 400GbE    |
|                                 | (default mode) / NDR IB; Single-port QSFP112; PCIe Gen5.0   |
|                                 | x16; 8 Arm cores; 16GB on board DDR; integrated BMC; Crypto |
|                                 | Enabled                                                     |
+---------------------------------+-------------------------------------------------------------+
| fw_version_current              | 32.41.1300                                                  |
+---------------------------------+-------------------------------------------------------------+
| pxe_version_current             | 3.7.0400                                                    |
+---------------------------------+-------------------------------------------------------------+
| uefi_version_current            | 14.34.0012                                                  |
+---------------------------------+-------------------------------------------------------------+
| uefi_version_virtio_blk_current | 22.4.0013                                                   |
+---------------------------------+-------------------------------------------------------------+
| uefi_version_virtio_net_current | 21.4.0013                                                   |
+---------------------------------+-------------------------------------------------------------+

chet@groundhog carbide on  mlx_device_subcmd_scout [!] via 🦀 v1.88.0
❯ sudo target/debug/forge-scout --mode standalone mlx-device describe 01:00.0 --format json
level=INFO msg="Running as Standalone...false" location="scout/src/main.rs:81"
{
  "pci_name": "01:00.0",
  "device_type": "BlueField3",
  "psid": "MT_0000001069",
  "device_description": "Nvidia BlueField-3 B3140H E-series HHHL SuperNIC; 400GbE (default mode) / NDR IB; Single-port QSFP112; PCIe Gen5.0 x16; 8 Arm cores; 16GB on board DDR; integrated BMC; Crypto Enabled",
  "part_number": "900-9D3D4-00EN-HA0_Ax",
  "fw_version_current": "32.41.1300",
  "pxe_version_current": "3.7.0400",
  "uefi_version_current": "14.34.0012",
  "uefi_version_virtio_blk_current": "22.4.0013",
  "uefi_version_virtio_net_current": "21.4.0013",
  "base_mac": "C4:70:BD:A4:EF:EE"
}

chet@groundhog carbide on  mlx_device_subcmd_scout [!] via 🦀 v1.88.0
❯ sudo target/debug/forge-scout --mode standalone mlx-device report --format json
level=INFO msg="Running as Standalone...false" location="scout/src/main.rs:81"
{
  "hostname": "groundhog",
  "timestamp": "2025-09-17T06:29:51.623724929Z",
  "devices": [
    {
      "pci_name": "01:00.0",
      "device_type": "BlueField3",
      "psid": "MT_0000001069",
      "device_description": "Nvidia BlueField-3 B3140H E-series HHHL SuperNIC; 400GbE (default mode) / NDR IB; Single-port QSFP112; PCIe Gen5.0 x16; 8 Arm cores; 16GB on board DDR; integrated BMC; Crypto Enabled",
      "part_number": "900-9D3D4-00EN-HA0_Ax",
      "fw_version_current": "32.41.1300",
      "pxe_version_current": "3.7.0400",
      "uefi_version_current": "14.34.0012",
      "uefi_version_virtio_blk_current": "22.4.0013",
      "uefi_version_virtio_net_current": "21.4.0013",
      "base_mac": "C4:70:BD:A4:EF:EE"
    }
  ],
  "filters": null
}
```

## Type of Change
<!-- Check one that best describes this MR -->
- [x] **Add** - New feature or capability
- [ ] **Change** - Changes in existing functionality  
- [ ] **Fix** - Bug fixes
- [ ] **Remove** - Removed features or deprecated functionality
- [x] **Internal** - Internal changes (refactoring, tests, docs, etc.)

## Related Tickets (Optional)
<!-- If applicable, provide JIRA or/and NVBugs ticket. If none, the MR itself will be referenced in changelog -->
JIRA: [FORGE-6102](https://jirasw.nvidia.com/browse/FORGE-6102), [FORGE-6256](https://jirasw.nvidia.com/browse/FORGE-6256)

## Breaking Changes
- [ ] This MR contains breaking changes

<!-- If checked above, describe the breaking changes and migration steps -->

## Testing
<!-- How was this tested? Check all that apply -->
- [ ] Unit tests added/updated
- [ ] Integration tests added/updated  
- [x] Manual testing performed
- [ ] No testing required (docs, internal refactor, etc.)

## Additional Notes
<!-- Any additional context, deployment notes, or reviewer guidance -->

See merge request nvmetal/carbide!4595