chore: Add debug code to troubleshoot failing update_health_report
We frequently see unit-tests failing when trying to update health reports. It is unclear why this happens, and whether its e.g. due to mismatching timestamps or transactions not being committed.

With this change, we will dump the Machine Entry whenever such an error is encountered in order to debug it. The code is not active in production.

E.g.

https://gitlab-master.nvidia.com/nvmetal/carbide/-/jobs/151561764

```
025-03-19T16:07:23.251523Z ERROR carbide::errors: Database Error: no rows returned by a query that expected to return at least one row file=api/src/db/machine.rs line=913 query=UPDATE machines SET network_status_observation = $1::json WHERE id = $2 AND
             (network_status_observation IS NULL
                OR (network_status_observation ? 'observed_at' AND network_status_observation->>'observed_at' <= $3)
            ) RETURNING id. location=./src/handlers/dpu.rs:652:5 handler='2: carbide::handlers::dpu::record_dpu_network_status::{{closure}}'
thread 'tests::maintenance::test_migrate_legacy_maintenance_mode_add_suppress_paging' panicked at api/src/tests/common/api_fixtures/mod.rs:1492:10:
```

https://gitlab-master.nvidia.com/nvmetal/carbide/-/jobs/151561764

```
2025-03-19T16:07:23.137851Z ERROR carbide::site_explorer: SiteExplorer run failed due to: DBError(DatabaseError { file: "api/src/db/machine.rs", line: 962, query: "update health report", source: RowNotFound })
```

See merge request nvmetal/carbide!3825