fix: rpc/admin_cli compile fails because missing library feature
## Description

`cargo make build` fails to build `admin_cli`

```
error[E0599]: no method named `to_csv` found for struct `Table` in the current scope
   --> crates/rpc/src/admin_cli.rs:313:19
    |
313 |             table.to_csv(&mut out).expect("Couldn't render CSV table");
    |                   ^^^^^^ method not found in `Table`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `carbide-rpc` (lib) due to 1 previous error
```

## Type of Change
<!-- Check one that best describes this MR -->
- [ ] **Add** - New feature or capability
- [ ] **Change** - Changes in existing functionality  
- [X] **Fix** - Bug fixes
- [ ] **Remove** - Removed features or deprecated functionality
- [ ] **Internal** - Internal changes (refactoring, tests, docs, etc.)

## Related Tickets (Optional)
<!-- If applicable, provide JIRA or/and NVBugs ticket. If none, the MR itself will be referenced in changelog -->
JIRA: <!-- e.g., [FORGE-1234](https://jirasw.nvidia.com/browse/FORGE-1234) or leave blank -->
NVBugs: <!-- e.g., [NVBugs-12345](https://nvbugspro.nvidia.com/bug/12345) or leave blank -->

## Breaking Changes
- [ ] This MR contains breaking changes

<!-- If checked above, describe the breaking changes and migration steps -->

## Testing
<!-- How was this tested? Check all that apply -->
- [ ] Unit tests added/updated
- [ ] Integration tests added/updated  
- [X] Manual testing performed
- [ ] No testing required (docs, internal refactor, etc.)

## Additional Notes

See merge request nvmetal/carbide!4777