fix(api-db): make the dpa-vni resource pool optional
Any new attempts to run `nico-api` without `[pools.dpa-vni]` set in the site config TOML file will result in `nico-api` crashing with the error:

```
Error: Resource pool 'dpa-vni' missing or full. Edit config file and restart.
```

This should be an optional resource pool since not all sites will need a `"dpa-vni"` resource pool. I think in the past when we managed all NICo sites, we'd prep all site configs with new resource pools, so it wasn't a big deal. Now, however, other teams/orgs/groups run their own NICo stack(s), so it is now up to them whether or not they need to configure this or not.

Signed-off-by: Chet Nichols III <chetn@nvidia.com>